name: Sync to Kaggle

on:
  push:
    branches: [ main ]
    paths:
      - 'notebooks/**'
      - 'src/**'
      - 'requirements.txt'
      - 'kernel-metadata.json'
      - '.github/workflows/kaggle-sync.yml'

jobs:
  push-kaggle:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Kaggle CLI
        run: pip install kaggle

      - name: Configure Kaggle credentials
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME }}\",\"key\":\"${{ secrets.KAGGLE_KEY }}\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Push notebook to Kaggle
        run: kaggle kernels push -p .